// flow-typed signature: f71497bcc4a403b3bdcc2bc7b77c1b5e
// flow-typed version: <<STUB>>/@types/jest_v^26.0.19/flow_v0.184.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
